services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            - FLASK_APP=server.py
            - FLASK_ENV=production
        env_file:
            - backend/.env
        volumes:
            - ../sf-data/database:/app/backend/instance
            - ../sf-data/logs:/app/backend/logs
        restart: unless-stopped

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - "2000:80"
        env_file:
            - frontend/.env
        depends_on:
            - backend
        restart: unless-stopped
