/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as PublicRouteImport } from "./routes/_public";
import { Route as PrivateRouteImport } from "./routes/_private";
import { Route as PublicIndexRouteImport } from "./routes/_public/index";
import { Route as PrivateDashboardRouteRouteImport } from "./routes/_private/dashboard/route";
import { ServerRoute as ApiAuthSplatServerRouteImport } from "./routes/api/auth/$";

const rootServerRouteImport = createServerRootRoute();

const PublicRoute = PublicRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateRoute = PrivateRouteImport.update({
  id: "/_private",
  getParentRoute: () => rootRouteImport,
} as any);
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PublicRoute,
} as any);
const PrivateDashboardRouteRoute = PrivateDashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => PrivateRoute,
} as any);
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootServerRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/dashboard": typeof PrivateDashboardRouteRoute;
  "/": typeof PublicIndexRoute;
}
export interface FileRoutesByTo {
  "/dashboard": typeof PrivateDashboardRouteRoute;
  "/": typeof PublicIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_private": typeof PrivateRouteWithChildren;
  "/_public": typeof PublicRouteWithChildren;
  "/_private/dashboard": typeof PrivateDashboardRouteRoute;
  "/_public/": typeof PublicIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/dashboard" | "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/dashboard" | "/";
  id:
    | "__root__"
    | "/_private"
    | "/_public"
    | "/_private/dashboard"
    | "/_public/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
}
export interface FileServerRoutesByFullPath {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
}
export interface FileServerRoutesByTo {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths: "/api/auth/$";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to: "/api/auth/$";
  id: "__root__" | "/api/auth/$";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_public": {
      id: "/_public";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_private": {
      id: "/_private";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof PrivateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_public/": {
      id: "/_public/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof PublicIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    "/_private/dashboard": {
      id: "/_private/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof PrivateDashboardRouteRouteImport;
      parentRoute: typeof PrivateRoute;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface PrivateRouteChildren {
  PrivateDashboardRouteRoute: typeof PrivateDashboardRouteRoute;
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDashboardRouteRoute: PrivateDashboardRouteRoute,
};

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren);

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
};

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
